server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name pimipan.work www.pimipan.work;
    ssl_certificate /etc/letsencrypt/live/pimipan.work/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pimipan.work/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /var/www/pimipan/current;
    index index.html;
    if ($host = www.pimipan.work) { return 301 https://pimipan.work$request_uri; }
    include /etc/nginx/snippets/pimipan-static.conf;
}
